/**
 * Phase 8C true-beginner symbol pack — score-biased simple recognizable glyphs.
 * kind=symbol for lighter reward-quality thresholds.
 */

import { normalizeConceptId, type CollectionId } from '../constants'
import type { ContentKind, SourceKind } from '../types'

export interface ExpansionTemplate {
	readonly id: string
	readonly titleRu: string
	readonly collectionId: CollectionId
	readonly conceptId: string
	readonly compositionId: string
	readonly family: string
	readonly kind: ContentKind
	readonly sourceKind: SourceKind
	readonly ascii: readonly string[]
}

function c(
	id: string,
	titleRu: string,
	collectionId: CollectionId,
	conceptId: string,
	compositionId: string,
	ascii: readonly string[],
	kind: ContentKind = 'symbol',
): ExpansionTemplate {
	return {
		id,
		titleRu,
		collectionId,
		conceptId: normalizeConceptId(conceptId),
		compositionId,
		family: `authored-${normalizeConceptId(conceptId)}`,
		kind,
		sourceKind: 'authored',
		ascii,
	}
}

export const B1000_SCALE_TRUE_BEGINNER: readonly ExpansionTemplate[] =
	Object.freeze([
		c('s8c-tb-arrow-up', 'Стрелка вверх мини', 'symbols', 'tb-arrow-up', 's5', [
			'..#..',
			'.###.',
			'#####',
			'..#..',
			'..#..',
		]),
		c('s8c-tb-arrow-dn', 'Стрелка вниз мини', 'symbols', 'tb-arrow-down', 's5', [
			'..#..',
			'..#..',
			'#####',
			'.###.',
			'..#..',
		]),
		c('s8c-tb-arrow-lt', 'Стрелка влево мини', 'symbols', 'tb-arrow-left', 's5', [
			'..#..',
			'.##..',
			'#####',
			'.##..',
			'..#..',
		]),
		c('s8c-tb-check', 'Галочка', 'symbols', 'tb-checkmark', 's5', [
			'....#',
			'...#.',
			'#.#..',
			'.#...',
			'.....',
		]),
		c('s8c-tb-xmark', 'Крестик знак', 'symbols', 'tb-x-mark', 's5', [
			'#...#',
			'.#.#.',
			'..#..',
			'.#.#.',
			'#...#',
		]),
		c('s8c-tb-diamond', 'Ромбик знак', 'symbols', 'tb-diamond', 's5', [
			'..#..',
			'.###.',
			'#####',
			'.###.',
			'..#..',
		]),
		c('s8c-tb-tri', 'Треугольник', 'symbols', 'tb-triangle', 's5', [
			'..#..',
			'.###.',
			'#####',
			'#####',
			'.....',
		]),
		c('s8c-tb-u', 'Подкова знак', 'symbols', 'tb-horseshoe', 's5', [
			'#...#',
			'#...#',
			'#...#',
			'#...#',
			'.###.',
		]),
		c('s8c-tb-c', 'Подкова открытая', 'symbols', 'tb-open-c', 's5', [
			'.###.',
			'#....',
			'#....',
			'#....',
			'.###.',
		]),
		c('s8c-tb-t', 'Тэ знак', 'symbols', 'tb-t-glyph', 's5', [
			'#####',
			'..#..',
			'..#..',
			'..#..',
			'..#..',
		]),
		c('s8c-tb-h', 'Аш знак', 'symbols', 'tb-h-glyph', 's5', [
			'#...#',
			'#...#',
			'#####',
			'#...#',
			'#...#',
		]),
		c('s8c-tb-o', 'Кольцо знак', 'symbols', 'tb-ring-o', 's5', [
			'.###.',
			'#...#',
			'#...#',
			'#...#',
			'.###.',
		]),
		c('s8c-tb-dotframe', 'Рамка точка', 'symbols', 'tb-frame-dot', 's5', [
			'#####',
			'#...#',
			'#.#.#',
			'#...#',
			'#####',
		]),
		c('s8c-tb-smile', 'Улыбка знак', 'symbols', 'tb-smile', 's5', [
			'.....',
			'#...#',
			'.....',
			'#...#',
			'.###.',
		]),
		c('s8c-tb-note', 'Нотка мини', 'music', 'tb-note', 's5', [
			'...#.',
			'...#.',
			'...#.',
			'.###.',
			'.###.',
		]),
		c('s8c-tb-bolt', 'Молния мини', 'weather', 'tb-bolt', 's5', [
			'..##.',
			'.##..',
			'#####',
			'..##.',
			'.##..',
		]),
		c('s8c-tb-peace', 'Пацифик мини', 'symbols', 'tb-peace', 's5', [
			'.###.',
			'#.#.#',
			'#.#.#',
			'#.#.#',
			'.###.',
		]),
		c('s8c-tb-yin', 'Инь-ян мини', 'symbols', 'tb-yinyang', 's5', [
			'.###.',
			'##..#',
			'#.#.#',
			'#..##',
			'.###.',
		]),
		c('s8c-tb-target', 'Мишень мини', 'sport', 'tb-target', 's5', [
			'.###.',
			'#...#',
			'#.#.#',
			'#...#',
			'.###.',
		]),
		c('s8c-tb-crown', 'Корона мини', 'symbols', 'tb-crown', 's5', [
			'#.#.#',
			'#####',
			'#####',
			'.....',
			'.....',
		]),
		c('s8c-tb-shield', 'Щит мини', 'symbols', 'tb-shield', 's5', [
			'#####',
			'#...#',
			'#...#',
			'.#.#.',
			'..#..',
		]),
		c('s8c-tb-leaf', 'Листок мини', 'plants', 'tb-leaf', 's5', [
			'..#..',
			'.###.',
			'#####',
			'.###.',
			'..#..',
		]),
		c('s8c-tb-drop', 'Капля мини', 'weather', 'tb-drop', 's5', [
			'..#..',
			'.###.',
			'#####',
			'#####',
			'.###.',
		]),
		c('s8c-tb-spark', 'Искра', 'symbols', 'tb-spark', 's5', [
			'..#..',
			'#.#.#',
			'.###.',
			'#.#.#',
			'..#..',
		]),
		c('s8c-tb-wave', 'Волна знак', 'sea', 'tb-wave', 's5', [
			'.....',
			'.#.#.',
			'#.#.#',
			'.....',
			'.....',
		]),
		c('s8c-tb-mountain', 'Гора знак', 'nature', 'tb-mountain', 's5', [
			'..#..',
			'.###.',
			'#####',
			'#####',
			'.....',
		]),
		c('s8c-tb-house', 'Дом знак', 'home', 'tb-house-glyph', 's5', [
			'..#..',
			'.###.',
			'#####',
			'#.#.#',
			'#####',
		]),
		c('s8c-tb-tree', 'Дерево знак', 'plants', 'tb-tree-glyph', 's5', [
			'..#..',
			'.###.',
			'#####',
			'..#..',
			'..#..',
		]),
		c('s8c-tb-fish', 'Рыба знак', 'sea', 'tb-fish-glyph', 's5', [
			'..#..',
			'.####',
			'##.#.',
			'.####',
			'..#..',
		]),
		c('s8c-tb-bird', 'Птица знак', 'birds', 'tb-bird-glyph', 's5', [
			'..##.',
			'.###.',
			'#####',
			'..#..',
			'.#...',
		]),
		c('s8c-tb-cat', 'Кот знак', 'animals', 'tb-cat-glyph', 's5', [
			'#...#',
			'.###.',
			'#.#.#',
			'#####',
			'#.#.#',
		]),
		c('s8c-tb-dog', 'Пёс знак', 'animals', 'tb-dog-glyph', 's5', [
			'#...#',
			'#####',
			'#.#.#',
			'.###.',
			'#...#',
		]),
		c('s8c-tb-car', 'Авто знак', 'transport', 'tb-car-glyph', 's5', [
			'.###.',
			'#####',
			'#####',
			'.#.#.',
			'.....',
		]),
		c('s8c-tb-plane', 'Самолёт знак', 'transport', 'tb-plane-glyph', 's5', [
			'..#..',
			'.###.',
			'#####',
			'..#..',
			'.###.',
		]),
		c('s8c-tb-boat', 'Корабль знак', 'sea', 'tb-boat-glyph', 's5', [
			'..#..',
			'..#..',
			'#####',
			'.###.',
			'.....',
		]),
		c('s8c-tb-rocket', 'Ракета знак', 'space', 'tb-rocket-glyph', 's5', [
			'..#..',
			'.###.',
			'.###.',
			'#.#.#',
			'#...#',
		]),
		c('s8c-tb-planet', 'Планета знак', 'space', 'tb-planet-glyph', 's5', [
			'.###.',
			'#...#',
			'#####',
			'#...#',
			'.###.',
		]),
		c('s8c-tb-music', 'Скрипичный ключ', 'music', 'tb-clef-glyph', 's5', [
			'..##.',
			'.#..#',
			'..##.',
			'.#...',
			'##...',
		]),
		c('s8c-tb-cup', 'Кубок знак', 'sport', 'tb-trophy', 's5', [
			'#.#.#',
			'#####',
			'.###.',
			'..#..',
			'.###.',
		]),
		c('s8c-tb-key', 'Ключ знак', 'objects', 'tb-key-glyph', 's5', [
			'.###.',
			'#...#',
			'.###.',
			'..#..',
			'..##.',
		]),
		c('s8c-tb-lock', 'Замок знак', 'objects', 'tb-lock-glyph', 's5', [
			'.###.',
			'#...#',
			'#####',
			'#.#.#',
			'#####',
		]),
		c('s8c-tb-gift', 'Бантик знак', 'objects', 'tb-gift-glyph', 's5', [
			'.#.#.',
			'#####',
			'#.#.#',
			'#####',
			'#####',
		]),
		c('s8c-tb-balloon', 'Шарик знак', 'objects', 'tb-balloon-glyph', 's5', [
			'.###.',
			'#####',
			'#####',
			'.###.',
			'..#..',
		]),
		c('s8c-tb-ice', 'Мороженое знак', 'food', 'tb-icecream', 's5', [
			'.###.',
			'#####',
			'.###.',
			'..#..',
			'..#..',
		]),
		c('s8c-tb-cake', 'Тортик знак', 'food', 'tb-cake-glyph', 's5', [
			'..#..',
			'.###.',
			'#####',
			'#.#.#',
			'#####',
		]),
		c('s8c-tb-apple', 'Яблоко знак', 'food', 'tb-apple-glyph', 's5', [
			'..#..',
			'.###.',
			'#####',
			'#####',
			'.###.',
		]),
		c('s8c-tb-cherry', 'Вишенка знак', 'food', 'tb-cherry-glyph', 's5', [
			'...#.',
			'..#..',
			'.#.#.',
			'#.#.#',
			'.#.#.',
		]),
		c('s8c-tb-mushroom', 'Грибочек', 'nature', 'tb-mushroom', 's5', [
			'.###.',
			'#####',
			'..#..',
			'..#..',
			'.###.',
		]),
		c('s8c-tb-flower', 'Цветок знак', 'plants', 'tb-flower-glyph', 's5', [
			'.#.#.',
			'.###.',
			'#####',
			'..#..',
			'..#..',
		]),
		c('s8c-tb-sun', 'Солнце знак', 'weather', 'tb-sun-glyph', 's5', [
			'#.#.#',
			'.###.',
			'#####',
			'.###.',
			'#.#.#',
		]),
		c('s8c-tb-cloud', 'Облако знак', 'weather', 'tb-cloud-glyph', 's5', [
			'.##..',
			'#####',
			'#####',
			'.....',
			'.....',
		]),
		c('s8c-tb-snow', 'Снежинка знак', 'weather', 'tb-snow-glyph', 's5', [
			'#.#.#',
			'.###.',
			'#####',
			'.###.',
			'#.#.#',
		]),
		c('s8c-tb-umbrella', 'Зонт знак', 'weather', 'tb-umbrella-glyph', 's5', [
			'.###.',
			'#####',
			'..#..',
			'..#..',
			'.#...',
		]),
		c('s8c-tb-bench', 'Скамейка знак', 'city', 'tb-bench-glyph', 's5', [
			'.....',
			'#####',
			'#...#',
			'#...#',
			'.....',
		]),
		c('s8c-tb-lamp', 'Фонарь знак', 'city', 'tb-lamp-glyph', 's5', [
			'.###.',
			'#...#',
			'.###.',
			'..#..',
			'..#..',
		]),
		c('s8c-tb-clock', 'Часы знак', 'objects', 'tb-clock-glyph', 's5', [
			'.###.',
			'#.#.#',
			'#.##.',
			'#...#',
			'.###.',
		]),
		c('s8c-tb-book', 'Книга знак', 'objects', 'tb-book-glyph', 's5', [
			'#####',
			'#.#.#',
			'#.#.#',
			'#.#.#',
			'#####',
		]),
		c('s8c-tb-pen', 'Перо знак', 'objects', 'tb-pen-glyph', 's5', [
			'...#.',
			'..#..',
			'.#...',
			'#....',
			'##...',
		]),
		c('s8c-tb-scissors', 'Ножницы знак', 'tools', 'tb-scissors', 's5', [
			'#...#',
			'.#.#.',
			'..#..',
			'.#.#.',
			'#...#',
		]),
		c('s8c-tb-hammer', 'Молоток знак', 'tools', 'tb-hammer', 's5', [
			'####.',
			'####.',
			'..#..',
			'..#..',
			'..#..',
		]),
		c('s8c-tb-wrench', 'Ключ гаечный', 'tools', 'tb-wrench', 's5', [
			'##..#',
			'##.#.',
			'..#..',
			'.#.##',
			'#..##',
		]),
		c('s8c-tb-music2', 'Нота двойная', 'music', 'tb-double-note', 's5', [
			'#..#.',
			'#..#.',
			'#.###',
			'###.#',
			'#...#',
		]),
		c('s8c-tb-flag', 'Флаг знак', 'symbols', 'tb-flag-glyph', 's5', [
			'#....',
			'####.',
			'####.',
			'#....',
			'#....',
		]),
		c('s8c-tb-anchor', 'Якорь знак', 'sea', 'tb-anchor-glyph', 's5', [
			'..#..',
			'.###.',
			'..#..',
			'#.#.#',
			'.###.',
		]),
		c('s8c-tb-compass', 'Компас знак', 'travel', 'tb-compass', 's5', [
			'..#..',
			'.#.#.',
			'#.#.#',
			'.#.#.',
			'..#..',
		]),
		c('s8c-tb-map', 'Карта знак', 'travel', 'tb-map-glyph', 's5', [
			'#####',
			'#.#.#',
			'#####',
			'#.#.#',
			'#####',
		]),
		c('s8c-tb-tent', 'Палатка знак', 'travel', 'tb-tent-glyph', 's5', [
			'..#..',
			'.###.',
			'#####',
			'#.#.#',
			'#.#.#',
		]),
		c('s8c-tb-camp', 'Костёр знак', 'travel', 'tb-campfire', 's5', [
			'..#..',
			'.#.#.',
			'.###.',
			'#.#.#',
			'.....',
		]),
		c('s8c-tb-boot', 'Сапог знак', 'clothing', 'tb-boot-glyph', 's5', [
			'..##.',
			'..##.',
			'.###.',
			'#####',
			'#...#',
		]),
		c('s8c-tb-hat', 'Шляпа знак', 'clothing', 'tb-hat-glyph', 's5', [
			'..#..',
			'.###.',
			'#####',
			'.....',
			'.....',
		]),
		c('s8c-tb-glasses', 'Очки знак', 'clothing', 'tb-glasses', 's5', [
			'.....',
			'##.##',
			'#.#.#',
			'##.##',
			'.....',
		]),
		c('s8c-tb-sock', 'Носок знак', 'clothing', 'tb-sock-glyph', 's5', [
			'.##..',
			'.##..',
			'.##..',
			'.###.',
			'..##.',
		]),
		c('s8c-tb-ball', 'Мяч знак', 'sport', 'tb-ball-glyph', 's5', [
			'.###.',
			'#.#.#',
			'#####',
			'#.#.#',
			'.###.',
		]),
		c('s8c-tb-medal', 'Медаль знак', 'sport', 'tb-medal-glyph', 's5', [
			'#...#',
			'.#.#.',
			'.###.',
			'#...#',
			'.###.',
		]),
		c('s8c-tb-whistle', 'Свисток знак', 'sport', 'tb-whistle-glyph', 's5', [
			'####.',
			'#..##',
			'####.',
			'..#..',
			'.....',
		]),
		// Dense 5×5 inspired by accepted B250 beginners (notebook/smiley/teapot).
		c('s8c-tb-dense-a', 'Плитка узорная', 'home', 'tb-dense-tile', 'd5', [
			'#####',
			'##.##',
			'#.#.#',
			'##.##',
			'#####',
		], 'object'),
		c('s8c-tb-dense-b', 'Окошко плотное', 'home', 'tb-dense-window', 'd5', [
			'#####',
			'#.#.#',
			'#####',
			'#.#.#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-c', 'Сейфик мини', 'objects', 'tb-dense-safe', 'd5', [
			'#####',
			'##.##',
			'#...#',
			'##.##',
			'#####',
		], 'object'),
		c('s8c-tb-dense-d', 'Радио плотное', 'objects', 'tb-dense-radio', 'd5', [
			'#####',
			'#.###',
			'#####',
			'#.#.#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-e', 'Печенье плотное', 'food', 'tb-dense-cookie', 'd5', [
			'.###.',
			'#####',
			'##.##',
			'#####',
			'.###.',
		], 'object'),
		c('s8c-tb-dense-g', 'Подушка узор', 'home', 'tb-dense-pillow', 'd5', [
			'#####',
			'#.#.#',
			'##.##',
			'#.#.#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-h', 'Конфетка', 'food', 'tb-dense-candy', 'd5', [
			'#.#.#',
			'.###.',
			'#####',
			'.###.',
			'#.#.#',
		], 'object'),
		c('s8c-tb-dense-j', 'Календарь лист', 'objects', 'tb-dense-calendar', 'd5', [
			'#####',
			'#.#.#',
			'#####',
			'#...#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-k', 'Чемоданчик', 'travel', 'tb-dense-case', 'd5', [
			'.###.',
			'#####',
			'#.#.#',
			'#####',
			'##.##',
		], 'object'),
		c('s8c-tb-dense-l', 'Кошелёк', 'objects', 'tb-dense-wallet', 'd5', [
			'#####',
			'#...#',
			'#####',
			'#.#.#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-n', 'Печатная плата', 'objects', 'tb-dense-pcb', 'd5', [
			'#.#.#',
			'.###.',
			'#.#.#',
			'.###.',
			'#.#.#',
		], 'object'),
		c('s8c-tb-dense-o', 'Мозаика мини', 'patterns', 'tb-dense-mosaic', 'd5', [
			'##.##',
			'##.##',
			'.....',
			'##.##',
			'##.##',
		], 'pattern'),
		c('s8c-tb-dense-p', 'Полосы горизонталь', 'patterns', 'tb-dense-hstripes', 'd5', [
			'#####',
			'.....',
			'#####',
			'.....',
			'#####',
		], 'pattern'),
		c('s8c-tb-dense-q', 'Клетка мелкая', 'patterns', 'tb-dense-grid', 'd6', [
			'######',
			'#.#.#.',
			'######',
			'.#.#.#',
			'######',
			'#.#.#.',
		], 'pattern'),
		c('s8c-tb-dense-r', 'Улыбка плотная', 'symbols', 'tb-dense-smile', 'd5', [
			'#####',
			'#.#.#',
			'#####',
			'#.###',
			'#####',
		]),
		c('s8c-tb-dense-s', 'Чайник плотный', 'drinks', 'tb-dense-kettle', 'd5', [
			'###.#',
			'#####',
			'##.##',
			'#####',
			'.###.',
		], 'object'),
		c('s8c-tb-dense-t', 'Крендель плотный', 'food', 'tb-dense-pretzel', 'd5', [
			'#.#.#',
			'#####',
			'.###.',
			'#####',
			'#.#.#',
		], 'object'),
		c('s8c-tb-dense-u', 'Замок плотный', 'objects', 'tb-dense-padlock', 'd5', [
			'.###.',
			'#...#',
			'#####',
			'#.#.#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-v', 'Мишка плотный', 'animals', 'tb-dense-bear', 'd5', [
			'#...#',
			'#####',
			'#.#.#',
			'#####',
			'.###.',
		], 'object'),
		c('s8c-tb-dense-w', 'Хрюшка плотная', 'animals', 'tb-dense-pig', 'd5', [
			'.###.',
			'#####',
			'#.#.#',
			'#####',
			'#...#',
		], 'object'),
		c('s8c-tb-dense-x', 'Ботинок плотный', 'clothing', 'tb-dense-boot', 'd5', [
			'..##.',
			'.###.',
			'#####',
			'####.',
			'#..#.',
		], 'object'),
		c('s8c-tb-dense-y', 'Смайлик плотный', 'symbols', 'tb-dense-smiley2', 'd5', [
			'#####',
			'#.#.#',
			'#####',
			'#.#.#',
			'#####',
		]),
		c('s8c-tb-dense-z', 'Блокнот узор', 'objects', 'tb-dense-notebook', 'd5', [
			'#####',
			'##.##',
			'#...#',
			'##.##',
			'#####',
		], 'object'),
		c('s8c-tb-dense-aa', 'Вафля квадрат', 'food', 'tb-dense-waffle', 'd5', [
			'#####',
			'#.#.#',
			'#####',
			'#.#.#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-ab', 'Кирпич с щелью', 'home', 'tb-dense-brick-gap', 'd5', [
			'#####',
			'#####',
			'#...#',
			'#####',
			'#####',
		], 'object'),
		c('s8c-tb-dense-ac', 'Рамка крест', 'symbols', 'tb-dense-frame-x', 'd5', [
			'#####',
			'#.#.#',
			'##.##',
			'#.#.#',
			'#####',
		]),
		c('s8c-tb-dense-ad', 'Пульт кнопки', 'objects', 'tb-dense-remote', 'd5', [
			'#####',
			'#.#.#',
			'#.#.#',
			'#.#.#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-ae', 'Шоколад плитка', 'food', 'tb-dense-chocolate', 'd5', [
			'#####',
			'##.##',
			'#####',
			'##.##',
			'#####',
		], 'object'),
		c('s8c-tb-dense-af', 'Кубик грани', 'objects', 'tb-dense-dice', 'd5', [
			'#####',
			'#.#.#',
			'#####',
			'#...#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-ag', 'Марка почтовая', 'objects', 'tb-dense-stamp', 'd5', [
			'#.#.#',
			'.###.',
			'#.#.#',
			'.###.',
			'#.#.#',
		], 'object'),
		c('s8c-tb-dense-ah', 'Батарейка', 'objects', 'tb-dense-battery', 'd5', [
			'.###.',
			'#####',
			'#.#.#',
			'#####',
			'#####',
		], 'object'),
		c('s8c-tb-dense-ai', 'Домик плотный', 'home', 'tb-dense-house2', 'd5', [
			'..#..',
			'.###.',
			'#####',
			'#.#.#',
			'#####',
		], 'object'),
		c('s8c-tb-dense-aj', 'Ёлка плотная', 'plants', 'tb-dense-fir2', 'd5', [
			'..#..',
			'.###.',
			'#####',
			'..#..',
			'..#..',
		], 'object'),
		c('s8c-exp-fill-a', 'Небоскрёб вечерний', 'city', 'tb-exp-skyline-a', 'e15', [
			'...............',
			'....###...###..',
			'...#####.#####.',
			'..##.#.##.#.##.',
			'.##..#..#..#.##',
			'###############',
			'##.#.#.#.#.#.##',
			'##.#.#.#.#.#.##',
			'###############',
			'##.#.#.#.#.#.##',
			'##.#.#.#.#.#.##',
			'###############',
			'##.....###...##',
			'##.....###...##',
			'###############',
		], 'object'),
		c('s8c-exp-fill-b', 'Верфь закатная', 'sea', 'tb-exp-shipyard-b', 'e15', [
			'...............',
			'..#.........#..',
			'.###...#...###.',
			'..#...###...#..',
			'..#..##.##..#..',
			'..#..##.##..#..',
			'###############',
			'##...........##',
			'##.##.....##.##',
			'##.##.....##.##',
			'###############',
			'....#######....',
			'...##.....##...',
			'..##..###..##..',
			'.##############',
		], 'scene'),
		c('s8c-tb-rect-a', 'Мостик короткий', 'city', 'tb-rect-bridge', 'r53', [
			'#...#',
			'#####',
			'#...#',
		], 'object'),
		c('s8c-tb-rect-b', 'Скамья парковая', 'city', 'tb-rect-bench', 'r53', [
			'#####',
			'#...#',
			'#...#',
		], 'object'),
		c('s8c-tb-rect-c', 'Полка настенная', 'home', 'tb-rect-shelf', 'r53', [
			'#####',
			'..#..',
			'..#..',
		], 'object'),
		c('s8c-tb-rect-d', 'Забор секция', 'home', 'tb-rect-fence', 'r64', [
			'#.#.#.',
			'######',
			'#.#.#.',
			'#.#.#.',
		], 'object'),
		c('s8c-tb-rect-e', 'Лестница ступени', 'home', 'tb-rect-stairs', 'r64', [
			'...###',
			'..###.',
			'.###..',
			'###...',
		], 'object'),
		c('s8c-tb-rect-f', 'Ограда зубцы', 'city', 'tb-rect-battlement', 'r64', [
			'#.#.#.',
			'######',
			'#....#',
			'#....#',
		], 'object'),
		c('s8c-tb-rect-g', 'Волна короткая', 'sea', 'tb-rect-wave', 'r53', [
			'.#.#.',
			'#.#.#',
			'.....',
		], 'symbol'),
		c('s8c-tb-rect-h', 'Рельсы путь', 'transport', 'tb-rect-rails', 'r64', [
			'#....#',
			'######',
			'#....#',
			'######',
		], 'object'),
		c('s8c-tb-rect-i', 'Мост арка мини', 'city', 'tb-rect-arch', 'r75', [
			'#.....#',
			'##...##',
			'#######',
			'#.....#',
			'#.....#',
		], 'object'),
		c('s8c-tb-rect-j', 'Лодка корпус', 'sea', 'tb-rect-hull', 'r75', [
			'..#....',
			'.###...',
			'#######',
			'.#####.',
			'.......',
		], 'object'),
		c('s8c-exp-fill-c', 'Замок туманов', 'travel', 'tb-exp-fog-castle', 'e15', [
			'.......#.......',
			'......###......',
			'.....#.#.#.....',
			'....#######....',
			'...##.....##...',
			'..##.###.###.##',
			'.##..###.###..#',
			'##...###.###.##',
			'###############',
			'##.#.#.#.#.#.##',
			'##.#.#.#.#.#.##',
			'###############',
			'##.....###...##',
			'##.....###...##',
			'###############',
		], 'object'),
	])
