export {
	FREE_HINTS_PER_DAY,
	FREE_TEACH_ME_PER_DAY,
	canUseHintWithoutRewarded,
	canUseTeachMeWithoutRewarded,
	consumeHintApply,
	consumeTeachMeReveal,
	createDefaultHelpAllowance,
	evaluateHintApplyGate,
	type HintApplyGate,
	formatFreeRemainingLabel,
	freeHintsRemaining,
	freeTeachMeRemaining,
	grantRewardedHintEntitlement,
	grantRewardedTeachMeEntitlement,
	rollHelpAllowanceToDay,
	willConsumeFreeHint,
	willConsumeFreeTeachMe,
	willConsumePendingHint,
	willConsumePendingTeachMe,
	type HelpAllowanceState,
	type HelpType,
} from './allowance'
